### ISSUE TITLE
Stop time

### ISSUE THREAD

**Issue by parkeral** [astifter/Drink#2]
It would be a nice feature to be able to set a stop time for alerts

**Comment by parkeral** [comment]
It would be a nice feature to be able to set a stop time for alerts

**Comment by astifter** [comment]
By having a start time, a target for the number of glasses and the interval there is an implicit stop time for the alerts (which is shown in the settings).

Since the four values are interdependent it would be confusing to make the stop time settable as well (since then either the interval or the starting time would have to be changed automatically). 

If you have an idea how this can be handled please put them forward!

**Comment by parkeral** [comment]
Please see the App Watango. They have the stop time incoroportated.I've been using it, but if yours had a stop time I'll stop an use yours. I don't always meet my goal.

Sent from Outlook

On Fri, May 22, 2015 at 1:39 PM -0700, "Andreas Neustifter" notifications@github.com wrote:
By having a start time, a target for the number of glasses and the interval there is an implicit stop time for the alerts (which is shown in the settings).

Since the four values are interdependent it would be confusing to make the stop time settable as well (since then either the interval or the starting time would have to be changed automatically).

If you have an idea how this can be handled please put them forward!

---

**Comment by astifter** [comment]
I'm on a trip for the next week but I will look into it after that.

**Comment by astifter** [comment]
I have not managed to find out what Watango does since I can't install the app only any of my iOS devices. 

From what I gather from the screenshots in Watango you can set 
- start time
- end time 
- an interval 
  which results in a certain number of alerts.

In Drink! you can set the 
- start time, 
- an interval and 
- the number of alerts 
  which results in a certain end time.

I can't see the advantage for the Watango way of doing it so for the time being you have to "influence" the end time by adjusting the number of glasses and the reminder interval.
(Also, when setting the times as in Watango the end time is not guaranteed since the time beween start and end time is not necessary dividable by the interval.)

**Comment by parkeral** [comment]
Thanks for looking into this issue.  My problem is I don't always reach my goal and the notifications go on throughout the nightThanks anyway

Sent from Outlook

On Thu, Jun 18, 2015 at 1:17 PM -0700, "Andreas Neustifter" notifications@github.com wrote:
Closed #2.

---

Reply to this email directly or view it on GitHub:
https://github.com/astifter/Drink/issues/2#event-334596922

**Comment by astifter** [comment]
Just to be sure: if you do not meet your goal the notifications will nevertheless stop at the time determined by start time, intervals and number of glasses. So the notifications do not continue just because you failed to log your drinks.
